### ISSUE TITLE
Infusion-related error when importing an artificer

### ISSUE THREAD

**Issue by edoreld** [MrPrimate/ddb-importer#480] opened 2024-05-05 19:14 UTC
**Describe the bug**
Error when importing a level 3 artificer from D&D Beyond

**To Reproduce**
1. Go to Foundry
2. Open Character Sheet
3. Enter Edit Mode
4. Click on D&D Beyond Icon
5. Enter url of character
6. Try to import

**Expected behavior**
Character imported successfully

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/973854/734fa711-bd06-4509-8c48-c7d2238ce0cd)

**Environment:**
 - Browser: N/A
 - Foundry Version Version 11 Stable 315
 - 5e System Version 3.1.2
 - Module Version 5.1.21
 - Does this behaviour occur with other modules disabled: Will find out, but other characters import work properly

**Additional context**

 - https://www.dndbeyond.com/characters/121928728

```
logger.js:84 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'value')
log @ logger.js:84
logger.js:82 DDB Importer | ERR > Error during parse: Cannot read properties of undefined (reading 'value')
log @ logger.js:82
logger.js:84 DDB Importer | ERR > JSON Fetch and Parse Error
log @ logger.js:84
logger.js:84 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'value')
log @ logger.js:84
logger.js:84 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'value')
    at parseInfusion (https://localhost/modules/ddb-importer/dist/main.js:39860:76)
    at DDBCharacter.getInventory (https://localhost/modules/ddb-importer/dist/main.js:53830:71)
    at async DDBCharacter._generateInventory (https://localhost/modules/ddb-importer/dist/main.js:50919:24)
    at async DDBCharacter._parseCharacter (https://localhost/modules/ddb-importer/dist/main.js:33240:7)
    at async DDBCharacter.getCharacterData (https://localhost/modules/ddb-importer/dist/main.js:33136:9)
    at async HTMLButtonElement.<anonymous> (https://localhost/modules/ddb-importer/dist/main.js:56565:11)
log @ logger.js:84
logger.js:84 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'value')
log @ logger.js:84
logger.js:84 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'value')
    at parseInfusion (https://localhost/modules/ddb-importer/dist/main.js:39860:76)
    at DDBCharacter.getInventory (https://localhost/modules/ddb-importer/dist/main.js:53830:71)
    at async DDBCharacter._generateInventory (https://localhost/modules/ddb-importer/dist/main.js:50919:24)
    at async DDBCharacter._parseCharacter (https://localhost/modules/ddb-importer/dist/main.js:33240:7)
    at async DDBCharacter.getCharacterData (https://localhost/modules/ddb-importer/dist/main.js:33136:9)
    at async HTMLButtonElement.<anonymous> (https://localhost/modules/ddb-importer/dist/main.js:56565:11)
log @ logger.js:84
logger.js:82 DDB Importer | ERR > Failure Object
```

**Comment by MrPrimate** [comment] 2024-05-05 19:54
Duplicate of #479 479

**Closed by MrPrimate** 2024-05-05 19:54 UTC
Labels: bug
