### ISSUE TITLE
Module Name (Character Glitch?) 

### ISSUE THREAD

**Issue by adrianpinnock** [MrPrimate/ddb-importer#169] opened 2021-09-03 23:31 UTC
Not certain how to explain this. Instead of the module being displayed as D&D Beyond Importer, it displayed as D&"amp;"D Beyond Importer. Doesn't seem to affect how the module functions but drives me crazy. (see screenshot below)

![image](https://user-images.githubusercontent.com/1498139/132074049-f04ffe31-5988-45cb-a792-dc53e8b85c88.png)

**Comment by MrPrimate** [comment] 2021-09-04 09:01
Duplicate of #168

**Closed by MrPrimate** 2021-09-04 09:01 UTC
