### ISSUE TITLE
AC and Spells not importing right

### ISSUE THREAD

**Issue by Silzin** [MrPrimate/ddb-importer#138] opened 2021-06-12 01:57 UTC
I am using 1.0.9 on Foundry 7.10.  prepared spells and effects that work with AC calculation are not syncing right.  what do I need to do on my end to get this working again?  Do I need to rule back to a previous version or something in the settings?

**Comment by MrPrimate** [comment] 2021-06-12 08:45
Please can you explain your issue a bit more and give an example? In addition can you upload a screen shot of the settings you're using on the Active Effects tab of the importer screen?

**Comment by theMagius0** [comment] 2021-07-07 18:49
I might be able to clarify @Silzin 's error report, as I was experiencing similar issues with AC using the exact same versions of the Module and Foundry.

I performed a series of tests using all 8 **Active Effect Option** checkboxes, and I was able to get things to "work" using _only_ the following options selected, and all others blank:

* Generate Active Effects for Equipment
* Generate Active Effects for Character Features/Racial Traits/Feats/Backgrounds
* Retain Active Effects

So, that's the tl;dr of how to _fix_ it.  

Here are the specific issues I was having with the ddb-importer and examples of how to reproduce them:

* Create a character with the **Unarmored Defense** feature in D&D Beyond.  Pull it over using the ddb-importer whilst either (1) selecting _none_ of the **Active Effect Option** checkboxes, or (2) selecting only the _Generate Active Effects for Equipment_ and _Generate Active Effects for Character Features/Racial Traits/Feats/Backgrounds_ checkboxes.  Observe that the character is not getting the +2 AC bonus.

* Create a character with the **Disciple of Life** feature in D&D Beyond.  Pull it over using the ddb-importer whilst either (1) only selecting the _Copy Active Effect from DAE Compendiums_ checkbox, or (2) selecting the Retain Active Effects option, or (3) selecting both of them.  Observe that, when casting healing spells, the bonus (2+ spell level) is applied _twice_ (when it should only be applied _once_).

* Create a character and equip them with a shield (no other armor) in D&D Beyond.  Pull it over using the ddb-importer whilst either (1) selecting _none_ of the checkboxes, or (2) selecting only the _Retain Active Effects_ checkbox, or (3) selecting the _Generate DAE Override ACs_ and the _Copy Active Effect from DAE Compendiums_ and the _Retain Active Effects_ checkboxes.  Observe that equipping or removing the shield has no effect on AC.  Now, open up a Compendium and add some armor (any type), and equip _that_.  The AC changes.  Now, try equipping the shield along with the Compendium armor.  No AC change.  

* (addendum to the above test)  If you were to only select _Copy Active Effect from DAE Compendiums_ and _Retain Active Effects_ in the test above, the Shield changes AC on its own.  And the Compendium armor changes AC on its own.  But equipping the two of them _together_ results in an erroneous AC.

These are but a _handful_ of test conditions that produce errors when moving characters from D&D Beyond to Foundry.  There are still about 20 or 30 more permutations that I haven't tested yet.

Regards,

**Comment by MrPrimate** [comment] 2021-07-07 20:26
@theMagius0 I suspect you are experiencing some _desired_/_expected_ results here.

It sounds like you have "Auto calculate AC" and "Auto calc base AC" set in the Dynamic Active Effects settings page. As per the FAQ and help page, these settings are not compatible with DDB Importer. If it is set then DAE will adjust the base AC and try and calculate the AC based on the equipment attached.

Retain Active Effects will copy over any existing effects on a character, so may explain some of the activity you are seeing as effects from previous imports are retained.

**Unarmored Defense** If no options are selected on the Active Effects tab the AC imports successfully. Please make sure that DAE has not placed an AC Effect on the character.

**Disciple of Life** if you are only selecting "Copy Active Effect from DAE Compendiums" then this is the expected behaviour as DDB Importer does not understand what effects are already loaded in DAE and if it is not generating them itself will add the extra to the appropriate spells on import. This is expected behaviour (even if it's not what you might expect)

The AC issues are the exact behaviour when another module(DAE) adds AC. It does this when items are added to the characters sheet.

**Comment by Silzin** [comment] 2021-07-07 22:56
Sorry for not getting back to you.  I think you to hit it.  I have experimented a lot and I think my first fix was just not use any Auto AC and set it my self.  But now the DDB importer Auto AC is working with active effects.  but I do not use the Auto AC stuff in DAE.

**Comment by theMagius0** [comment] 2021-07-08 01:27
Sincere apologies, @MrPrimate , but apparently I'm still not doing something correctly.

I have unchecked the two (2) boxes regarding AC calculation in **Dynamic effects using After Effects** settings.

* If I have a Cleric with the **Disciple of Life** feature, I'm seeing the bonuses (2 + spell level) calculated _twice_ in the chat window for the roll, when they should only be calculated _once_.

* If I have a Sorcerer use her **Shield** spell, I'm not seeing any effect on AC whatsoever.

I've looked at the FAQ located at: https://github.com/MrPrimate/ddb-importer/blob/main/FAQ.md.

Can you please direct me to the 'help' page?

Thx,

**Comment by MrPrimate** [comment] 2021-07-08 06:12
@theMagius0 can you provide a character URL and a screenshot of the settings your using during import on the Active Effects tab?

**Comment by theMagius0** [comment] 2021-07-08 12:14
Cleric URL is here: https://www.dndbeyond.com/profile/theMagius/characters/52514332.

Sorcerer URL is here: https://www.dndbeyond.com/profile/theMagius/characters/52514710

All **Active Effect Options** are unchecked because selecting some of them were yielding even stranger results than when I left them all unchecked (e.g. Shield spell would only show Concentration--not the Shield icon itself).

Is there a detailed tutorial on each of the **Active Effect Options**, by chance?  Perhaps I've not selected the correct permutation to achieve the result I'm looking for?

Or, perhaps I should be removing (unchecking) the **DAE** module whilst using the ddb-importer?  And then enable the DAE after characters have been imported into Foundry?  Would this yield better results?

Thx,

**Comment by MrPrimate** [comment] 2021-07-08 17:27
@theMagius0 it sounds like there are effects on your character already that are being transferred across.

The shield spell will only apply the effect when cast and you need a module like midi qol to do this for you.

You can see my importing these characters with the effects correctly:

https://cdn.discordapp.com/attachments/862745177521258528/862745238904373308/shield.webm
https://cdn.discordapp.com/attachments/862745177521258528/862745252497588264/d-o-life.webm

**Comment by theMagius0** [comment] 2021-07-08 17:44
Appreciate you looking into this, sir.

I suppose it must be something else in my Foundry setup which is causing these errors, then.

I'll try and investigate on my end.

You may close this issue at your convenience.

Thx,

**Comment by MrPrimate** [comment] 2021-07-08 21:18
@theMagius0 if you struggle to resolve folks in the discord might be able to help you figure it out.

**Closed by MrPrimate** 2021-07-08 21:18 UTC
