### ISSUE TITLE
Shield Spell incorrectly imported

### ISSUE THREAD

**Issue by Brimcon** [MrPrimate/ddb-importer#55] opened 2020-12-21 00:27 UTC
When importing a character with a shield in their equipment and using the DAE Import option, the Shield Spell gets imported rather than the shield Item

**Comment by MrPrimate** [comment] 2020-12-21 19:05
Hi @Brimcon this calls the function provided by the DAE module to add/swap items/features/spells, so the problem is upstream I'm afraid.

**Comment by MrPrimate** [comment] 2021-01-02 23:56
Resolved in local implementation of DAE compendium match function

**Closed by MrPrimate** 2021-01-02 23:56 UTC
Labels: bug
