### ISSUE TITLE
Error when importing character: TypeError: Cannot read property 'dndbeyond' of undefined

### ISSUE THREAD

**Issue by sjondeux** [MrPrimate/ddb-importer#6] opened 2020-11-09 12:33 UTC
First of all, thanks for this awesome tool. Importing other characters went flawlessly, but I'm running into this error when importing a warlock (not sure if this is relevant). I'm also seeing a lot of "The specified value "+0" cannot be parsed, or is out of range." in the console.

I get this error after clicking the 'Start Import' button:

![image](https://user-images.githubusercontent.com/8201657/98538187-ab515f00-228a-11eb-86dc-f3614020af1e.png)

It imports the attributes and biography just fine, but the spell list remains empty.

This is the character I am trying to import: https://www.dndbeyond.com/characters/1350556

**Comment by MrPrimate** [comment] 2020-11-10 20:59
Thanks for the report, I'll dig into it, I can't reproduce in the current dev version, so hoping this is fixed in the next release.

**Comment by sjondeux** [comment] 2020-11-10 22:29
Thanks for checking, I'll try again when the new version is released then.

**Comment by Ekizu** [comment] 2020-11-14 17:07
Hi, I also encounter this issue, with a warlock and a rogue.

![image](https://user-images.githubusercontent.com/46567637/99152711-b1d54180-26a3-11eb-9836-8db0ac9d68a1.png)

Characters I have the issue with:

https://www.dndbeyond.com/profile/LucileCauchy/characters/38377881
https://www.dndbeyond.com/profile/FIRHJEY/characters/38378235

**Software versions:**

- FoundryVTT 0.7.7
- DnD5e - Fifth Edition System 1.1.1
- D&D Beyond Importer 0.0.9

**Comment by Ekizu** [comment] 2020-11-15 19:35
I checked with the last version today (0.0.10), no more issue when importing the characters I had issues with !
Great work !

**Closed** 2020-11-16 08:44 UTC

**Comment by sjondeux** [comment] 2020-11-16 09:09
Same here, I just checked. No issues anymore. Awesome job!
