### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by EtienneDroletBegin** [MrPrimate/ddb-importer#483] opened 2024-05-12 21:27 UTC
after Updating my FoundryVTT to the latest version (11) as well as the DnD system (3.1.2), i have been unable to import characters, it simply gives me the error "Cannot read properties of undefined (reading '0')"

i tried resetting the cobalt key and reinstalling the module but nothing worked

**Comment by MrPrimate** [comment] 2024-05-13 06:27
Duplicate of https://github.com/MrPrimate/ddb-importer/issues/406 see original issue for cause and resolution.

**Closed** 2024-05-13 06:27 UTC
Labels: bug
