### ISSUE TITLE
Optional Class Features Don't Import

### ISSUE THREAD

**Issue by mattdomville** [MrPrimate/ddb-importer#272] opened 2022-09-29 20:43 UTC
Optional Class Features from Tasha's don't seem to be making the transition to my instance of Foundry
Examples:
Monk's Dedicated Weapon, Ki-Fueled Attack, Quickened Healing
Wizard's Cantrip Formulas
Cleric's Harness Divine Power

**Comment by MrPrimate** [comment] 2022-09-30 09:48
Duplicate of #147

**Closed by MrPrimate** 2022-09-30 09:48 UTC

**Comment by mattdomville** [comment] 2022-09-30 13:34
Thanks for the update! I'd seen the other entry and hadn't realized it was related.
The changelog seemed to imply that Optional Class Features were included. 
Are all of the Optional Class Features from Tasha's excluded?

**Comment by MrPrimate** [comment] 2022-09-30 20:57
They should be coming through on character import, but I don't think they do for the class/feature import
